neotube/users/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length, ValidationError

from neotube.models import User


class RegisterForm(FlaskForm):
    username = StringField(
        "Username:", validators=[DataRequired(), Length(min=5, max=15)]
    )
    password = PasswordField("Password:", validators=[DataRequired(), Length(min=5)])
    confirm_password = PasswordField(
        "Confirm Password:", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        if User.query.filter_by(username=username.data).first():
            raise ValidationError("An user with chosen username already exits!")


class LoginForm(FlaskForm):
    username = StringField("Username:", validators=[DataRequired()])
    password = PasswordField("Password:", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Sign In")

neotube/playlists/routes.py
import os

from flask import current_app, Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required

from neotube import db
from neotube.models import Playlist, Video
from neotube.playlists.forms import EditForm, NewForm
from neotube.playlists.utils import save_thumb

playlists = Blueprint("playlists", __name__)

@playlists.route("/playlist/<int:playlist_id>")
def playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    videos = Video.query.filter(Video.playlists.contains(playlist)).order_by(Video.date.desc()).paginate(page=request.args.get("page", 1, type=int), per_page=12)
    return render_template("playlists/playlist.html", title=playlist.title, videos=videos, playlist=playlist)

@playlists.route("/playlist/new", methods=["GET", "POST"])
@login_required
def new_playlist():
    if not current_user.videos:
        flash(f"You need to upload a video first.", "danger")
        return redirect(url_for("videos.upload"))
    form = NewForm()
    form.ids.choices = [(vid.id, vid.title) for vid in current_user.videos]
    if form.validate_on_submit():
        playlist = Playlist(title=form.title.data, user=current_user)
        db.session.add(playlist)
        db.session.commit()
        if form.thumbnail.data:
            playlist.thumbnail = save_thumb(f"{playlist.id}.jpeg", form.thumbnail.data)
        for video_id in form.ids.data:
            video = Video.query.get(video_id)
            video.playlists.append(playlist)
        db.session.commit()
        flash(f"'{playlist.title}' has been successfully created!", "success")
        return redirect(url_for("users.user_playlists", username=current_user.username))
    return render_template("playlists/new_playlist.html", form=form, title="New Playlist")

@playlists.route("/playlist/<int:playlist_id>/edit", methods=["GET", "POST"])
@login_required
def edit_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    if playlist.user != current_user:
        abort(403)
    form = EditForm()
    form.ids.choices = [(vid.id, vid.title) for vid in playlist.user.videos]
    if form.validate_on_submit():
        playlist.title = form.title.data
        if form.thumbnail.data:
            playlist.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        playlist.videos = []
        for video_id in form.ids.data:
            video = Video.query.get(video_id)
            playlist.videos.append(video)
        db.session.commit()
        flash(f"'{playlist.title}' has been successfully updated!", "success")
        return redirect(url_for("playlists.playlist", playlist_id=playlist.id))
    elif request.method == "GET":
        form.title.data = playlist.title
    return render_template("playlists/edit_playlist.html", title="Edit", form=form)


@playlists.route("/playlist/<int:playlist_id>/delete")
@login_required
def delete_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    if playlist.user != current_user:
        abort(403)
    db.session.delete(playlist)
    db.session.commit()
    if playlist.thumbnail != "default.jpeg":
        path = os.path.join(current_app.root_path, "static/playlists", playlist.thumbnail)
        if os.path.isfile(path):
            os.remove(path)
    flash(f"'{playlist.title}' has been successfully deleted!", "success")
    return redirect(url_for("users.user_playlists", username=current_user.username))

neotube/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from neotube import bcrypt, db
from neotube.models import User, Video, Playlist
from neotube.users.forms import LoginForm, RegisterForm

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("videos.index"))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        db.session.add(User(username=form.username.data, password=hashed_password))
        db.session.commit()
        flash(
            f"Account created for '{form.username.data}'! You may now login.", "success"
        )
        return redirect(url_for("users.login"))
    return render_template("users/register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("videos.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            if next_page:
                return redirect(next_page)
            return redirect(url_for("videos.index"))
        else:
            flash(f"Bad credentials!", "danger")
    return render_template("users/login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("videos.index"))


@users.route("/user/<string:username>")
def user_videos(username):
    user = User.query.filter_by(username=username).first_or_404()
    videos = Video.query.filter_by(user=user).order_by(Video.date.desc())
    if current_user == user:
        videos = videos.paginate(page=request.args.get("page", 1, type=int), per_page=11)
    else:
        videos = videos.paginate(page=request.args.get("page", 1, type=int), per_page=12)

    return render_template("users/user_videos.html", videos=videos, user=user, playlists=len(user.playlists))

@users.route("/user/<string:username>/playlists")
def user_playlists(username):
    user = User.query.filter_by(username=username).first_or_404()
    playlists = Playlist.query.filter_by(user=user).order_by(Playlist.date.desc())
    if current_user == user:
        playlists = playlists.paginate(page=request.args.get("page", 1, type=int), per_page=11)
    else:
        playlists = playlists.paginate(page=request.args.get("page", 1, type=int), per_page=12)
    return render_template("users/user_playlists.html", videos=len(user.videos), user=user, playlists=playlists)

neotube/videos/routes.py
import os

import markdown
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required

from neotube import db
from neotube.models import Video
from neotube.videos.forms import EditForm, UploadForm
from neotube.videos.utils import save_thumb

videos = Blueprint("videos", __name__)


@videos.route("/")
def index():
    query = request.args.get("q")
    if query:
        return render_template(
            "videos/index.html",
            videos=Video.query.filter(Video.title.contains(query)).paginate(
                page=request.args.get("page", 1, type=int), per_page=12
            ),
        )
    return render_template(
        "videos/index.html",
        videos=Video.query.order_by(Video.date.desc()).paginate(
            page=request.args.get("page", 1, type=int), per_page=12
        ),
    )


@videos.route("/video/<int:video_id>")
def video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.description:
        video.description = markdown.markdown(video.description)
    return render_template("videos/video.html", title=video.title, video=video)


@videos.route("/video/upload", methods=["GET", "POST"])
@login_required
def upload():
    form = UploadForm()
    if form.validate_on_submit():
        video = Video(
            title=form.title.data,
            description=form.description.data,
            video="_",
            user=current_user,
        )
        db.session.add(video)
        db.session.commit()
        filename = f"{video.id}.mp4"
        form.video.data.save(
            os.path.join(current_app.root_path, "static/videos", filename)
        )
        video.video = filename
        if form.thumbnail.data:
            video.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        db.session.commit()
        flash(f"'{form.title.data}' has been successfully uploaded!", "success")
        return redirect(url_for("users.user_videos", username=current_user.username))
    return render_template("videos/upload.html", form=form, title="Upload")


@videos.route("/video/<int:video_id>/edit", methods=["GET", "POST"])
@login_required
def edit_video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.user != current_user:
        abort(403)
    form = EditForm()
    if form.validate_on_submit():
        video.title = form.title.data
        video.description = form.description.data
        if form.thumbnail.data:
            video.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        db.session.commit()
        flash(f"'{video.title}' has been successfully updated!", "success")
        return redirect(url_for("videos.video", video_id=video.id))
    elif request.method == "GET":
        form.title.data = video.title
        form.description.data = video.description
    return render_template("videos/edit.html", title="Edit", form=form)


@videos.route("/video/<int:video_id>/delete")
@login_required
def delete_video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.user != current_user:
        abort(403)
    db.session.delete(video)
    db.session.commit()
    path = os.path.join(current_app.root_path, "static/videos", video.video)
    if os.path.isfile(path):
        os.remove(path)
    if video.thumbnail != "default.jpeg":
        path = os.path.join(current_app.root_path, "static/videos", video.thumbnail)
        if os.path.isfile(path):
            os.remove(path)
    flash(f"'{video.title}' has been successfully deleted!", "success")
    return redirect(url_for("users.user_videos", username=current_user.username))

neotube/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center">Login</h1>
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.username.label(class="form-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.password.label(class="form-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control") }}
        {% endif %}
    </div>
    <div class="form-check mb-3 col-lg-6 mx-auto">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
<small class="text-muted text-center d-block">
    Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>.
</small>
{% endblock content %}

neotube/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center">Register</h1>
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.username.label(class="form-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.password.label(class="form-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.confirm_password.label(class="form-label") }}
        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
<small class="text-muted text-center d-block">
    Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in</a>.
</small>
{% endblock content %}

neotube/templates/users/user_playlists.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center mb-0">{{ user.username }}</h1>
<small class="d-block text-muted text-center mb-3">Uploaded <a href="{{ url_for('users.user_videos', username=user.username) }}" class="text-decoration-none">{{ videos }} video(s)</a> and created <a href="{{ url_for('users.user_playlists', username=user.username) }}" class="text-decoration-none">{{ playlists.total }} playlist(s)</a> since {{ user.date.strftime('%B %dth, %Y') }}.</small>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-3">
    {% if current_user == user %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('playlists.new_playlist') }}"><img src="{{ url_for('static', filename='assets/new_playlist.jpeg') }}" class="card-img-top"></a>
            <div class="card-body">
                <p class="card-title text-center fw-bold"><a class="link-dark text-decoration-none" href="{{ url_for('playlists.new_playlist') }}">New Playlist</a></p>
                <p class="card-text text-center"><small class="text-muted">Create a new playlist!</small></p>
            </div>
        </div>
    </div>
    {% endif %}
    {% for playlist in playlists.items %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('playlists.playlist', playlist_id=playlist.id) }}">
                <img src="{{ url_for('static', filename='playlists/' + playlist.thumbnail) }}" class="card-img-top">
            </a>
            <div class="card-body">
                <p class="card-title text-truncate text-center fw-bold"><a href="{{ url_for('playlists.playlist', playlist_id=playlist.id) }}" class="link-dark text-decoration-none">{{ playlist.title }}</a></p>
                <p class="card-text text-center">
                    <small class="text-muted">
                        {{ playlist.date.strftime('%B %dth, %Y') }}.
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if playlists.pages > 1 %}
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if playlists.has_prev %}
        <li class="page-item">
            {% else %}
            <li class="page-item disabled">
                {% endif %}
                <a class="page-link" href="{{ url_for('users.user_playlists', username=user.username, page=playlists.page-1) }}">Previous</a>
            </li>
            {% for page_num in playlists.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
            {% if playlists.page == page_num %}
            <li class="page-item active"><a class="page-link" href="{{ url_for('users.user_playlists', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item "><a class="page-link" href="{{ url_for('users.user_playlists', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if playlists.has_next %}
            <li class="page-item">
                {% else %}
                <li class="page-item disabled">
                    {% endif %}
                    <a class="page-link" href="{{ url_for('users.user_playlists', username=user.username, page=playlists.page+1) }}">Next</a>
                </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}

neotube/templates/users/user_videos.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center mb-0">{{ user.username }}</h1>
<small class="d-block text-muted text-center mb-3">Uploaded <a href="{{ url_for('users.user_videos', username=user.username) }}" class="text-decoration-none">{{ videos.total }} video(s)</a> and created <a href="{{ url_for('users.user_playlists', username=user.username) }}" class="text-decoration-none">{{ playlists }} playlist(s)</a> since {{ user.date.strftime('%B %dth, %Y') }}.</small>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-3">
    {% if current_user == user %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('videos.upload') }}"><img src="{{ url_for('static', filename='assets/upload.jpeg') }}" class="card-img-top"></a>
            <div class="card-body">
                <p class="card-title text-center fw-bold"><a class="link-dark text-decoration-none" href="{{ url_for('videos.upload') }}">Upload</a></p>
                <p class="card-text text-center"><small class="text-muted">Submit a new video!</small></p>
            </div>
        </div>
    </div>
    {% endif %}
    {% for video in videos.items %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('videos.video', video_id=video.id) }}">
                <img src="{{ url_for('static', filename='videos/' + video.thumbnail) }}" class="card-img-top">
            </a>
            <div class="card-body">
                <p class="card-title text-truncate text-center fw-bold"><a href="{{ url_for('videos.video', video_id=video.id) }}" class="link-dark text-decoration-none">{{ video.title }}</a></p>
                <p class="card-text text-center">
                    <small class="text-muted">
                        {{ video.date.strftime('%B %dth, %Y') }}.
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if videos.pages > 1 %}
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if videos.has_prev %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('users.user_videos', username=user.username, page=videos.page-1) }}">Previous</a>
        </li>
        {% for page_num in videos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if videos.page == page_num %}
        <li class="page-item active"><a class="page-link" href="{{ url_for('users.user_videos', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item "><a class="page-link" href="{{ url_for('users.user_videos', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if videos.has_next %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('users.user_videos', username=user.username, page=videos.page+1) }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}