neotube/videos/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class UploadForm(FlaskForm):
    title = StringField("Title:", validators=[DataRequired()])
    description = TextAreaField("Description: (Optional)")
    thumbnail = FileField(
        "Thumbnail: (Optional)",
        validators=[FileAllowed(["jpg", "jpeg", "png", "webp"])],
    )
    video = FileField("Video:", validators=[FileAllowed(["mp4"]), FileRequired()])
    submit = SubmitField("Upload")


class EditForm(FlaskForm):
    title = StringField("Title:", validators=[DataRequired()])
    description = TextAreaField("Description:")
    thumbnail = FileField(
        "Thumbnail:",
        validators=[FileAllowed(["jpg", "jpeg", "png", "webp"])],
    )
    submit = SubmitField("Edit")

neotube/videos/routes.py
import os

import markdown
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required

from neotube import db
from neotube.models import Video
from neotube.videos.forms import EditForm, UploadForm
from neotube.videos.utils import save_thumb

videos = Blueprint("videos", __name__)


@videos.route("/")
def index():
    query = request.args.get("q")
    if query:
        return render_template(
            "videos/index.html",
            videos=Video.query.filter(Video.title.contains(query)).paginate(
                page=request.args.get("page", 1, type=int), per_page=12
            ),
        )
    return render_template(
        "videos/index.html",
        videos=Video.query.order_by(Video.date.desc()).paginate(
            page=request.args.get("page", 1, type=int), per_page=12
        ),
    )


@videos.route("/video/<int:video_id>")
def video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.description:
        video.description = markdown.markdown(video.description)
    return render_template("videos/video.html", title=video.title, video=video)


@videos.route("/video/upload", methods=["GET", "POST"])
@login_required
def upload():
    form = UploadForm()
    if form.validate_on_submit():
        video = Video(
            title=form.title.data,
            description=form.description.data,
            video="_",
            user=current_user,
        )
        db.session.add(video)
        db.session.commit()
        filename = f"{video.id}.mp4"
        form.video.data.save(
            os.path.join(current_app.root_path, "static/videos", filename)
        )
        video.video = filename
        if form.thumbnail.data:
            video.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        db.session.commit()
        flash(f"'{form.title.data}' has been successfully uploaded!", "success")
        return redirect(url_for("users.user_videos", username=current_user.username))
    return render_template("videos/upload.html", form=form, title="Upload")


@videos.route("/video/<int:video_id>/edit", methods=["GET", "POST"])
@login_required
def edit_video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.user != current_user:
        abort(403)
    form = EditForm()
    if form.validate_on_submit():
        video.title = form.title.data
        video.description = form.description.data
        if form.thumbnail.data:
            video.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        db.session.commit()
        flash(f"'{video.title}' has been successfully updated!", "success")
        return redirect(url_for("videos.video", video_id=video.id))
    elif request.method == "GET":
        form.title.data = video.title
        form.description.data = video.description
    return render_template("videos/edit.html", title="Edit", form=form)


@videos.route("/video/<int:video_id>/delete")
@login_required
def delete_video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.user != current_user:
        abort(403)
    db.session.delete(video)
    db.session.commit()
    path = os.path.join(current_app.root_path, "static/videos", video.video)
    if os.path.isfile(path):
        os.remove(path)
    if video.thumbnail != "default.jpeg":
        path = os.path.join(current_app.root_path, "static/videos", video.thumbnail)
        if os.path.isfile(path):
            os.remove(path)
    flash(f"'{video.title}' has been successfully deleted!", "success")
    return redirect(url_for("users.user_videos", username=current_user.username))

neotube/templates/videos/edit.html
{% extends "base.html" %}
{% block head %}
<style>
textarea,
pre {
    -moz-tab-size : 4;
      -o-tab-size : 4;
         tab-size : 4;
}
</style>
{% endblock head %}
{% block content %}
<h1 class="text-center">Edit</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.title.label(class="form-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.description.label(class="form-label") }}
        {% if form.description.errors %}
        {{ form.description(class="form-control font-monospace is-invalid", rows=7) }}
        <div class="invalid-feedback">
            {% for error in form.description.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.description(class="form-control font-monospace", rows=7) }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.thumbnail.label(class="form-label") }}
        {% if form.thumbnail.errors %}
        {{ form.thumbnail(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.thumbnail.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.thumbnail(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
{% endblock content %}
{% block script %}
<script>
    // Enables tab for description
    desc = document.querySelector("#description");
    desc.onkeydown = (e)=> {
        if (e.keyCode == 9) {
            let val = desc.value,
                start = desc.selectionStart,
                end = desc.selectionEnd;
            desc.value = val.substring(0, start) + '\t' + val.substring(end);
            desc.selectionStart = desc.selectionEnd = start + 1;
            return false;
        }
    }
</script>
{% endblock script %}

neotube/templates/videos/index.html
{% extends "base.html" %}
{% block content %}
{% if query %}
<p>You searched for {{ query }}.</p>
{% endif %}
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-3">
    {% for video in videos.items %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('videos.video', video_id=video.id) }}"><img src="{{ url_for('static', filename='videos/' + video.thumbnail) }}" class="card-img-top"></a>
            <div class="card-body">
                <p class="card-title text-truncate text-center fw-bold"><a href="{{ url_for('videos.video', video_id=video.id) }}" class="link-dark text-decoration-none">{{ video.title }}</a></p>
                <p class="card-text text-center">
                    <small class="text-muted d-md-none d-lg-inline">
                        By <a href="{{ url_for('users.user_videos', username=video.user.username) }}" class="text-decoration-none">{{ video.user.username }}</a> on {{ video.date.strftime('%B %dth, %Y') }}.
                    </small>
                    <small class="text-muted d-none d-md-inline d-lg-none">
                        By <a href="{{ url_for('users.user_videos', username=video.user.username) }}" class="text-decoration-none">{{ video.user.username }}</a> on {{ video.date.strftime('%x') }}.
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if videos.pages > 1 %}
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if videos.has_prev %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('videos.index', page=videos.page-1) }}">Previous</a>
        </li>
        {% for page_num in videos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if videos.page == page_num %}
        <li class="page-item active"><a class="page-link" href="{{ url_for('videos.index', page=page_num) }}">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item "><a class="page-link" href="{{ url_for('videos.index', page=page_num) }}">{{ page_num }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if videos.has_next %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('videos.index', page=videos.page+1) }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}

neotube/templates/videos/upload.html
{% extends "base.html" %}
{% block head %}
<style>
textarea,
pre {
    -moz-tab-size : 4;
      -o-tab-size : 4;
         tab-size : 4;
}
</style>
{% endblock head %}
{% block content %}
<h1 class="text-center">Upload</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.title.label(class="form-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.description.label(class="form-label") }}
        {% if form.description.errors %}
        {{ form.description(class="form-control font-monospace is-invalid", rows=7) }}
        <div class="invalid-feedback">
            {% for error in form.description.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.description(class="form-control font-monospace", rows=7) }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.thumbnail.label(class="form-label") }}
        {% if form.thumbnail.errors %}
        {{ form.thumbnail(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.thumbnail.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.thumbnail(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.video.label(class="form-label") }}
        {% if form.video.errors %}
        {{ form.video(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.video.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.video(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
{% endblock content %}
{% block script %}
<script>
    // Enables tab for description
    desc = document.querySelector("#description");
    desc.onkeydown = (e)=> {
        if (e.keyCode == 9) {
            let val = desc.value,
                start = desc.selectionStart,
                end = desc.selectionEnd;
            desc.value = val.substring(0, start) + '\t' + val.substring(end);
            desc.selectionStart = desc.selectionEnd = start + 1;
            return false;
        }
    }
</script>
{% endblock script %}

neotube/templates/videos/video.html
{% extends "base.html" %}
{% block head %}
<style>
#description h1 { font-size: 1.5rem; }
#description h2 { font-size: 1.35rem; }
#description h3 { font-size: 1.20rem; }
#description h4 { font-size: 1.05rem; }
#description h5 { font-size: 1rem; }
</style>
{% endblock head %}
{% block content %}
<div>
    <video src="{{ url_for('static', filename='videos/' + video.video) }}" controls class="col-12"></video>
    {% if current_user == video.user %}
    <h1 class="fs-3 mb-0">
        <span role="button" data-bs-toggle="dropdown">{{ video.title }}</span>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('videos.edit_video', video_id=video.id) }}">Edit</a></li>
            <li><a class="dropdown-item" href=".modal" data-bs-toggle="modal">Delete</a></li>
        </ul>
    </h1>
    <div class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-0">
                    <h5 class="modal-title">Are you sure?</h5>
                    <button class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">You will <strong>NOT</strong> be abble to recover this video!</div>
                <div class="modal-footer border-0">
                    <button class="btn btn-outline-primary" data-bs-toggle="modal">Cancel</button>
                    <a class="btn btn-danger" role="button" href="{{ url_for('videos.delete_video', video_id=video.id) }}">Delete</a>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h1 class="fs-3 mb-0">{{ video.title }}</h1>
    {% endif %}
    <small class="text-muted d-block mb-3">
        By <a href="{{ url_for('users.user_videos', username=video.user.username) }}" class="text-decoration-none">{{ video.user.username }}</a> on {{ video.date.strftime('%B %dth, %Y') }}.
    </small>
    {% if video.description %}
    <div id="description">{{ video.description |safe }}</div>
    {% endif %}
</div>
{% endblock content %}