neotube/playlists/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, SelectMultipleField
from wtforms.validators import DataRequired


class NewForm(FlaskForm):
    title = StringField("Title:", validators=[DataRequired()])
    thumbnail = FileField(
        "Thumbnail: (Optional)",
        validators=[FileAllowed(["jpg", "jpeg", "png", "webp"])],
    )
    ids = SelectMultipleField("Select the videos:", coerce=int, validators=[DataRequired()])
    submit = SubmitField("Create")


class EditForm(FlaskForm):
    title = StringField("Title:", validators=[DataRequired()])
    thumbnail = FileField(
        "Thumbnail:",
        validators=[FileAllowed(["jpg", "jpeg", "png", "webp"])],
    )
    ids = SelectMultipleField("Select the videos:", coerce=int, validators=[DataRequired()])
    submit = SubmitField("Edit")

neotube/playlists/routes.py
import os

from flask import current_app, Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required

from neotube import db
from neotube.models import Playlist, Video
from neotube.playlists.forms import EditForm, NewForm
from neotube.playlists.utils import save_thumb

playlists = Blueprint("playlists", __name__)

@playlists.route("/playlist/<int:playlist_id>")
def playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    videos = Video.query.filter(Video.playlists.contains(playlist)).order_by(Video.date.desc()).paginate(page=request.args.get("page", 1, type=int), per_page=12)
    return render_template("playlists/playlist.html", title=playlist.title, videos=videos, playlist=playlist)

@playlists.route("/playlist/new", methods=["GET", "POST"])
@login_required
def new_playlist():
    if not current_user.videos:
        flash(f"You need to upload a video first.", "danger")
        return redirect(url_for("videos.upload"))
    form = NewForm()
    form.ids.choices = [(vid.id, vid.title) for vid in current_user.videos]
    if form.validate_on_submit():
        playlist = Playlist(title=form.title.data, user=current_user)
        db.session.add(playlist)
        db.session.commit()
        if form.thumbnail.data:
            playlist.thumbnail = save_thumb(f"{playlist.id}.jpeg", form.thumbnail.data)
        for video_id in form.ids.data:
            video = Video.query.get(video_id)
            video.playlists.append(playlist)
        db.session.commit()
        flash(f"'{playlist.title}' has been successfully created!", "success")
        return redirect(url_for("users.user_playlists", username=current_user.username))
    return render_template("playlists/new_playlist.html", form=form, title="New Playlist")

@playlists.route("/playlist/<int:playlist_id>/edit", methods=["GET", "POST"])
@login_required
def edit_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    if playlist.user != current_user:
        abort(403)
    form = EditForm()
    form.ids.choices = [(vid.id, vid.title) for vid in playlist.user.videos]
    if form.validate_on_submit():
        playlist.title = form.title.data
        if form.thumbnail.data:
            playlist.thumbnail = save_thumb(f"{video.id}.jpeg", form.thumbnail.data)
        playlist.videos = []
        for video_id in form.ids.data:
            video = Video.query.get(video_id)
            playlist.videos.append(video)
        db.session.commit()
        flash(f"'{playlist.title}' has been successfully updated!", "success")
        return redirect(url_for("playlists.playlist", playlist_id=playlist.id))
    elif request.method == "GET":
        form.title.data = playlist.title
    return render_template("playlists/edit_playlist.html", title="Edit", form=form)


@playlists.route("/playlist/<int:playlist_id>/delete")
@login_required
def delete_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    if playlist.user != current_user:
        abort(403)
    db.session.delete(playlist)
    db.session.commit()
    if playlist.thumbnail != "default.jpeg":
        path = os.path.join(current_app.root_path, "static/playlists", playlist.thumbnail)
        if os.path.isfile(path):
            os.remove(path)
    flash(f"'{playlist.title}' has been successfully deleted!", "success")
    return redirect(url_for("users.user_playlists", username=current_user.username))

neotube/templates/playlists/edit_playlist.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center">Edit Playlist</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.title.label(class="form-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.thumbnail.label(class="form-label") }}
        {% if form.thumbnail.errors %}
        {{ form.thumbnail(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.thumbnail.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.thumbnail(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.ids.label(class="form-label") }}
        {% if form.ids.errors %}
        {{ form.ids(class="form-control form-select overflow-auto is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.ids.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.ids(class="form-control form-select overflow-auto") }}
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
{% endblock content %}

neotube/templates/playlists/new_playlist.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center">New Playlist</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.title.label(class="form-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.thumbnail.label(class="form-label") }}
        {% if form.thumbnail.errors %}
        {{ form.thumbnail(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.thumbnail.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.thumbnail(class="form-control") }}
        {% endif %}
    </div>
    <div class="mb-3 col-lg-6 mx-auto">
        {{ form.ids.label(class="form-label") }}
        {% if form.ids.errors %}
        {{ form.ids(class="form-control form-select overflow-auto is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.ids.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.ids(class="form-control form-select overflow-auto") }}
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        {{ form.submit(class="btn col-12 col-lg-6 btn-outline-primary") }}
    </div>
</form>
{% endblock content %}

neotube/templates/playlists/playlist.html
{% extends "base.html" %}
{% block content %}
{% if current_user == playlist.user %}
<h1 class="text-center mb-0">
    <span role="button" data-bs-toggle="dropdown">{{ title }}</span>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{{ url_for('playlists.edit_playlist', playlist_id=playlist.id) }}">Edit</a></li>
        <li><a class="dropdown-item" href=".modal" data-bs-toggle="modal">Delete</a></li>
    </ul>
</h1>
<div class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title">Are you sure?</h5>
                <button class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">You will <strong>NOT</strong> be abble to recover this playlist!</div>
            <div class="modal-footer border-0">
                <button class="btn btn-outline-primary" data-bs-toggle="modal">Cancel</button>
                <a class="btn btn-danger" role="button" href="{{ url_for('playlists.delete_playlist', playlist_id=playlist.id) }}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% else %}
<h1 class="text-center mb-0">{{ title }}</h1>
{% endif %}
<small class="d-block text-muted text-center mb-3">Created on {{ playlist.date.strftime('%B %dth, %Y') }} by <a class="text-decoration-none" href="{{ url_for('users.user_playlists', username=playlist.user.username) }}">{{ playlist.user.username }}</a>.</small>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-3">
    {% for video in videos.items %}
    <div class="col">
        <div class="card">
            <a href="{{ url_for('videos.video', video_id=video.id) }}">
                <img src="{{ url_for('static', filename='videos/' + video.thumbnail) }}" class="card-img-top">
            </a>
            <div class="card-body">
                <p class="card-title text-truncate text-center fw-bold"><a href="{{ url_for('videos.video', video_id=video.id) }}" class="link-dark text-decoration-none">{{ video.title }}</a></p>
                <p class="card-text text-center">
                    <small class="text-muted">
                        {{ video.date.strftime('%B %dth, %Y') }}.
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if videos.pages > 1 %}
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if videos.has_prev %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('playlists.playlist', playlist_id=playlist.id, page=videos.page-1) }}">Previous</a>
        </li>
        {% for page_num in videos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if videos.page == page_num %}
        <li class="page-item active"><a class="page-link" href="{{ url_for('playlists.playlist', playlist_id=playlist.id, page=page_num) }}">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item "><a class="page-link" href="{{ url_for('playlists.playlist', playlist_id=playlist.id, page=page_num) }}">{{ page_num }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if videos.has_next %}
        <li class="page-item">
        {% else %}
        <li class="page-item disabled">
        {% endif %}
            <a class="page-link" href="{{ url_for('playlists.playlist', playlist_id=playlist.id, page=videos.page+1) }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}